# Generated by Django 5.0.3 on 2024-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task2", "0002_remove_vacancy_salary_from_remove_vacancy_salary_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="salary_from",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_to",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
