# Generated by Django 5.0.3 on 2024-03-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task2", "0003_vacancy_salary_from_vacancy_salary_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_from",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_to",
        ),
    ]
