# Generated by Django 5.0.3 on 2024-03-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task3", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="marja",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=200),
        ),
    ]
