# Generated by Django 5.0.3 on 2024-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task3", "0002_alter_product_marja_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="marja",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="package_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
