# Generated by Django 5.0.3 on 2024-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task3", "0003_alter_product_marja_alter_product_package_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="encrypted_marja",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="encrypted_price",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
