# Generated by Django 5.0.3 on 2024-03-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task3", "0005_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
    ]
