# Generated by Django 5.0.3 on 2024-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task4", "0003_alter_card_options_alter_goal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("In progress", "In progress"),
                    ("Finished", "Finished"),
                ],
                default="Not started",
                max_length=20,
            ),
        ),
    ]
